workflows:
  ios-build:
    name: iOS Build for .NET MAUI
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple-credentials  # Stocke ton certificat et profil de provisionnement dans Codemagic
        - dotnet-7           # Utilise .NET 7 (ou modifie selon ta version)
      vars:
        BUNDLE_ID: "com.tonentreprise.smartpharma"
        XCODE_SCHEME: "SmartPharma5"
        XCODE_WORKSPACE: "SmartPharma5"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Install .NET SDK
        script: |
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$DOTNET_ROOT:$PATH
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 8.0.100
      - name: Check .NET version
        script: dotnet --version
      - name: Restore dependencies
        script: dotnet restore
      - name: Build the iOS project
        script: |
          dotnet build SmartPharma5.sln -c Release -f net8.0-ios --no-restore
      - name: Publish the iOS App
        script: |
          dotnet publish SmartPharma5.sln -c Release -f net8.0-ios --no-restore --output ./output
    artifacts:
      - output/**/*
    publishing:
      email:
        recipients:
          - "abdessalemennour@gmail.com"
